[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
actix-cors = "0.7.0"
actix-files = "0.6.6"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
clap = "4.5.29"
