[package]
name = "backend"
version = "0.2.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
actix-cors = "0.7.0"
actix-files = "0.6.6"
serde_json = "1.0.138"
clap = "4.5.29"
tempfile = "3.16.0"
sha2 = "0.10.8"
serde = { version = "1.0.217", features = ["derive"] }
uuid = { version = "1.15.1", features = ["v4"] }
anyhow = "1.0.97"
tar = "0.4.43"
